# -*- coding: utf-8 -*-
{
    'name': 'BugFix - Stock',
    'version': '17.0.0.0.12',
    'summary': 'Studio-to-Python port for BugFix-Stock',
    'author': 'Jinasena Agricultural Machinery (Pvt) Ltd.',
    'category': 'Inventory',
    'license': 'LGPL-3',
    # Do NOT depend on studio_customization -- Odoo SH does not ship
    # a manifest for it, listing it causes install skip.
    'depends': ['base_setup', 'stock'],
    'data': [
        'security/ir_model_pins.xml',
        'security/ir.model.access.csv',
        'data/server_actions.xml',
        'data/automations.xml',
        'data/act_windows.xml',
        'views/x_con_consolidated_hea_studio_ported.xml',
        'views/x_con_consolidated_lin_studio_ported.xml',
        'views/x_consignment_charge_h_studio_ported.xml',
        'views/x_consignment_charge_l_studio_ported.xml',
        'views/x_consignment_header_studio_ported.xml',
        'views/x_consignment_line_studio_ported.xml',
        'views/x_journal_types_studio_ported.xml',
        'views/x_material_request_studio_ported.xml',
        'views/x_misc_charge_codes_studio_ported.xml',
        'views/x_sales_report_type_studio_ported.xml',
        'views/x_tariffmaster_studio_ported.xml',
        'views/x_temp_consignment_hea_studio_ported.xml',
        'views/stock_return_picking_studio_ported.xml',
        'views/stock_landed_cost_studio_ported.xml',
        'views/stock_location_studio_ported.xml',
        'views/stock_picking_type_studio_ported.xml',
        'views/stock_warehouse_studio_ported.xml',
        'views/stock_picking_studio_ported.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}