# -*- coding: utf-8 -*-
from odoo import fields, models


class StockPicking(models.Model):
    _inherit = 'stock.picking'

    x_studio_analytic_account = fields.Many2one('account.analytic.account', string='Analytic Account', readonly=True)
    x_studio_budget_created = fields.Boolean(string='Budget Created', readonly=True)
    x_studio_cancelled = fields.Boolean(string='Cancelled', readonly=True)
    x_studio_cash_full_payment_made = fields.Boolean(string='Cash Full Payment Made', readonly=True, store=False)
    x_studio_consignment_no = fields.Many2one('x_consignment_header', string='Consignment No')
    x_studio_created_from_help_ticket = fields.Many2one('helpdesk.ticket', string='Created from Help Ticket')
    x_studio_created_from_material_request_no = fields.Many2one('x_material_request', string='Created from Material Request No')
    x_studio_custom_clearance_no = fields.Char(string='Custom Clearance No', readonly=True)
    x_studio_factory_repair = fields.Boolean(string='Factory Repair')
    x_studio_fsm_task_done = fields.Boolean(string='FSM Task Done', readonly=True, store=False)
    x_studio_fully_paid_so = fields.Boolean(string='Fully Paid SO', readonly=True, store=False)
    x_studio_gl_account_status = fields.Selection([], string='G/L Account Status')
    x_studio_helpdesk_ticket_id = fields.Many2one('helpdesk.ticket', string='Helpdesk Ticket Id')
    x_studio_journal_type = fields.Many2one('x_journal_types', string='Journal Type')
    x_studio_maintenance_request_ = fields.Many2one('maintenance.request', string='Maintenance Request #')
    x_studio_mj_in = fields.Boolean(string='MJ IN', readonly=True)
    x_studio_mj_out = fields.Boolean(string='MJ OUT', readonly=True)
    x_studio_movement_journal = fields.Boolean(string='Movement Journal', readonly=True)
    x_studio_need_approval = fields.Boolean(string='Need Approval', readonly=True, store=False)
    x_studio_offset_account_updated = fields.Boolean(string='Offset Account Updated')
    x_studio_picking_count = fields.Boolean(string='Picking Count')
    x_studio_pr_type = fields.Selection([], string='PR Type', readonly=True)
    x_studio_quotation_type = fields.Selection([], string='Quotation Type', readonly=True)
    x_studio_quotation_type_2 = fields.Selection([], string='Quotation Type-2', readonly=True)
    x_studio_received_at_centre = fields.Boolean(string='Received at Centre')
    x_studio_related_field_zZDiA = fields.Selection([], string='New Related Field', readonly=True)
    x_studio_repair_payment_made = fields.Boolean(string='Repair Payment Made', readonly=True, store=False)
    x_studio_repair_return_location = fields.Boolean(string='Repair Return Location', readonly=True)
    x_studio_return_receipt_location = fields.Many2one('stock.location', string='Return Receipt Location', readonly=True)
    x_studio_return_sequence = fields.Many2one('ir.sequence', string='Return Sequence', readonly=True)
    x_studio_sales_order = fields.Many2one('sale.order', string='Sales Order')
    x_studio_sequence_code = fields.Char(string='Sequence Code', readonly=True)
    x_studio_supplier_invoice_number = fields.Char(string='Supplier Invoice Number')
    x_studio_supplier_invoice_number_1 = fields.Char(string='Supplier Invoice Number', readonly=True)
    x_studio_task_status = fields.Boolean(string='Task Status', readonly=True, store=False)
    x_studio_ticket_sales_order = fields.Many2one('sale.order', string='Ticket Sales Order', readonly=True, store=False)
    x_studio_transfer_approval = fields.Boolean(string='Transfer Approval')
    x_studio_transfer_approved = fields.Boolean(string='Transfer Approved')
    x_studio_transfer_rejected = fields.Boolean(string='Transfer Rejected')
    x_studio_transfer_request_sent = fields.Boolean(string='Transfer Request Sent')
    x_studio_ttt = fields.Boolean(string='TTT')
    x_studio_type_of_operation = fields.Selection([], string='Type of Operation', readonly=True)
    x_studio_update_consignment = fields.Boolean(string='Update Consignment')
    x_studio_user_location_validation = fields.Boolean(string='User Location Validation', readonly=True, store=False)
    x_studio_user_location_validation_2 = fields.Boolean(string='User Location Validation 2')
    x_studio_valid_factory_repair = fields.Boolean(string='Valid Factory Repair', readonly=True, store=False)
    x_studio_valid_transfer_lines = fields.Boolean(string='Valid Transfer Lines', readonly=True, store=False)
    x_studio_validation = fields.Char(string='Validation')
    x_studio_xxx = fields.Boolean(string='XXX')
    x_x_studio_create_from_transfer_1__account_move_count = fields.Integer(string='Create From Transfer count', store=False)
    x_x_studio_created_from_transfer__account_move_count = fields.Integer(string='Created From Transfer count', store=False)
